kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: python:3.10-slim
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: main
      DB_USERNAME: main
      DB_PASSWORD: main
      JWT_SECRET_KEY: "super secret key"
    commands:
      - sleep 10 # Wait for PostgreSQL service starting
      - pip install pipenv && pipenv install --dev --deploy --system
      - pipenv run flake8 app tests
      - pipenv run autoflake --remove-all-unused-imports --remove-unused-variables --recursive app tests
      - pipenv run black --check --diff app tests
      - pipenv run isort --check-only app tests
      - pipenv run mypy app tests
      - pipenv run pytest
      - pip freeze > requirements.txt

  - name: image
    image: plugins/docker
    settings:
      registry: registry.okami101.io
      repo: registry.okami101.io/adr1enbe4udou1n/fastapi-realworld
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password

  # - name: deploy
  #   image: sinlead/drone-kubectl
  #   settings:
  #     kubernetes_server:
  #       from_secret: kube_server
  #     kubernetes_cert:
  #       from_secret: kube_ca
  #     kubernetes_token:
  #       from_secret: kube_token
  #   commands:
  #     - kubectl rollout restart deployments/fastapi -n conduit

services:
  - name: db
    image: postgres:14
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main

trigger:
  event:
    - push
    - pull_request
