[tool.poetry]
name = "fastapi-realworld-example-app"
version = "0.1.0"
description = ""
authors = ["Adrien Beaudouin <adrien.beaudouin@outlook.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
uvicorn = { extras = ["standard"], version = "^0.22.0" }
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
alembic = "^1.8.1"
python-slugify = "^8.0.0"
pydantic = { extras = ["email"], version = "^2.0.0" }
requests = "^2.28.1"
psycopg2-binary = "^2.9.5"
httpx = "^0.24.0"
sqlalchemy = { extras = ["mypy"], version = "^2.0.7" }
pydantic-settings = "^2.0.1"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.0.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"
isort = "^5.10.1"
black = "^23.0.0"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
faker = "^18.0.0"
types-python-slugify = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
