[tool.poetry]
name = "fastapi-realworld-example-app"
version = "0.1.0"
description = ""
authors = ["Adrien Beaudouin <adrien.beaudouin@outlook.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.81.0"
uvicorn = { extras = ["standard"], version = "^0.18.3" }
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
alembic = "^1.8.1"
python-slugify = "^6.1.2"
pydantic = { extras = ["email"], version = "^1.10.1" }
requests = "^2.28.1"
psycopg2-binary = "^2.9.5"

[tool.poetry.group.dev.dependencies]
autoflake = "^1.5.2"
flake8 = "^5.0.4"
mypy = "^0.971"
isort = "^5.10.1"
black = "^22.6.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
sqlalchemy-stubs = "^0.4"
Faker = "^14.1.1"
types-python-slugify = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
