version: "3"

tasks:
  prepare:
    cmds:
      - pip install poetry
  install:
    cmds:
      - poetry install
  lint:
    cmds:
      - poetry run ruff check app tests alembic
      - poetry run ruff format --check app tests alembic
      - poetry run mypy app tests
  build:
    cmds:
      - poetry run alembic upgrade head
      - poetry export --output requirements.txt
  test:
    cmds:
      - poetry run pytest --cov --cov-report=term --cov-report=xml
